sudo: required
services:
  - docker

before_install:
  - docker build -t mrkmlchr/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mrkmlchr/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-689332895404"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"